### ISSUE TITLE
ava online faucet not working, several days already

### ISSUE THREAD

**Issue by nlpvan-paul** [ava-labs/gecko#222]
**Describe the bug**
the faucet on  - https://faucet.ava.network/

**To Reproduce**
generate an address, 
send ava from - https://faucet.ava.network/ to this address, 
check balance on address - shows still 0

**Expected behavior**
balance showing the funds sent

**Screenshots**
...

**Operating System**
ubuntu 20.04

**Additional context**
running ./ava daemon , connect to testnet
using rest api to create addtess, get balance
did try repeatedly for several days june/04,05,06

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
@nlpvan-paul 
Hi, thanks for reporting and for your patience.

The network is more stable right now and the faucet should be working.
Is it working for you now?

In the future, see the #testnet-status channel on our [Discord channel](https://docs.ava.network/v1.0/en/tutorials/creating-a-local-testnet/) for the most up-to-date info on the status of the faucet, network, etc.

**Comment by nlpvan-paul** [comment]
No, the faucet is still not working - after trying to get ava and check balances few times just 2 hours ago.In my case I do not have any initial test funds and the node is not on genesis validators list.
paul.

    On Tuesday, June 9, 2020, 9:25:36 AM PDT, danlaine <notifications@github.com> wrote:  
 
 


@nlpvan-paul
Hi, thanks for reporting and for your patience.

The network is more stable right now and the faucet should be working.
Is it working for you now?

In the future, see the #testnet-status channel on our Discord channel for the most up-to-date info on the status of the faucet, network, etc.

**Comment by danlaine** [comment]
@nlpvan-paul I believe this will be resolved once you upgrade to 0.5.4 and complete bootstrapping. Let me know if that isn't the case

**Comment by nlpvan-paul** [comment]
Hi,I did get the 0.5.4 and the node did bootstrap. But, I still do not receive funds after sending from faucet site.Paul.

    On Tuesday, June 9, 2020, 1:44:43 PM PDT, danlaine <notifications@github.com> wrote:  
 
 


@nlpvan-paul I believe this will be resolved once you upgrade to 0.5.4 and complete bootstrapping. Let me know if that isn't the case

**Comment by danlaine** [comment]
Hi @nlpvan-paul are you still having this issue after upgrading to 0.5.7?

**Comment by danlaine** [comment]
Closing this issue for now. Let me know if you have any issues going forward.
